spring:
  application:
    name: authorization-server
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/h?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  redis:
    host: 192.168.57.120
    port: 6379
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.pojo

server:
  port: 8081